KERNEL_SOURCE=https://github.com/AndroPlus-org/android_kernel_xiaomi_sdm845
KERNEL_SOURCE_BRANCH=MIUI12.5
KERNEL_CONFIG=cettlefish_defconfig
KERNEL_IMAGE_NAME=Image.gz-dtb
ARCH=arm64
EXTRA_CMDS:LD=ld.lld

# Clang
## Custom
USE_CUSTOM_CLANG=false
CUSTOM_CLANG_SOURCE=
CUSTOM_CLANG_BRANCH=

### if your set USE CUSTOM CLANG to false than DO NOT CHANGE CUSTOM CMDS
CUSTOM_CMDS:CLANG_TRIPLE=aarch64-linux-gnu-

## AOSP
CLANG_BRANCH=android10-release
CLANG_VERSION=r383902b

# GCC
ENABLE_GCC_ARM64=true
ENABLE_GCC_ARM32=true

# KernelSU flags
ENABLE_KERNELSU=true
KERNELSU_TAG=v0.6.1

# Configuration
DISABLE-LTO=false
DISABLE_CC_WERROR=true
ADD_KPROBES_CONFIG=true
ADD_OVERLAYFS_CONFIG=true

# Ccache
ENABLE_CCACHE=true

# DTBO image
NEED_DTBO=false

# Build boot images
BUILD_BOOT_IMG=true
SOURCE_BOOT_IMAGE=https://media-jsyz-fy-person.js6oss.ctyunxs.cn/PERSONCLOUD/662c317d-10c0-49bb-b7d1-929371221394.img?response-content-disposition=attachment%3Bfilename%3D%22boot.img%22%3Bfilename*%3DUTF-8%27%27boot.img&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-CLIENTTYPEIN=WEB&Signature=1hK6jSHi80IKcHpvD8DHAYGv4S8%3D&AWSAccessKeyId=0Lg7dAq3ZfHvePP8DKEU&x-amz-userLevel=0&Expires=1688364684&x-amz-limitrate=51200&x-amz-FSIZE=67092480&x-amz-UID=27684593&x-amz-UFID=22519175233772921
